export function calculateAcAnnualForManyYears (acAnnual, rate, lifespan = 25, degradationRate = 0.005, escalationRate = 0.025) {
  let currentYear = new Date().getFullYear();
    const dataPerYear = {};
   
    dataPerYear[currentYear] = {acAnnual, amount: (acAnnual * rate)};
    for (let i = 1; i < lifespan; i++) {
      // power of every year is calculated based on prevous year's power factoring degradation rate
      const newPower = dataPerYear[currentYear].acAnnual - (dataPerYear[currentYear].acAnnual * degradationRate);
      // Amount is calculated based on newly calculated power factoring escalation rate
      let newRate = rate * ( 1 + escalationRate );
      dataPerYear[currentYear + 1] = {acAnnual: newPower, amount: (newPower  * newRate)};
      currentYear ++;
      rate = newRate;
    }
    return dataPerYear;
}

export function calculateAcMonthlyForManyYears (acMonthly, monthlyAmount, rate, lifespan = 25, degradationRate = 0.005, escalationRate = 0.025) {
  let currentYear = new Date().getFullYear();
  const monthlyDataPerYear = {};
  const powerConsumption = monthlyAmount / 0.12;
  //calculate the acMontly produced by the solar system and its value and the remaining grid bill
  //first element in monthlyDataPerYear object is the first year values based on these value the next years will be calculate
  monthlyDataPerYear[currentYear] = {acMonthly, acMonthlyValue: acMonthly.map(e => e * rate)  , grid: acMonthly.map(e => (e - powerConsumption) * rate)}
  let newRate = rate * ( 1 + escalationRate );
  for (let i = 1; i < lifespan; i++) {
    let acMontlyAfterDegredation = monthlyDataPerYear[currentYear].acMonthly.map(e => e - (e * degradationRate ));
    let acMontlyAfterDegredationValue = acMontlyAfterDegredation.map(e => e * newRate);
    let restOfGridAfterDegredation = acMontlyAfterDegredation.map(e => (e - powerConsumption) * newRate)
    
    monthlyDataPerYear[currentYear + 1] = {acMonthly: acMontlyAfterDegredation, acMonthlyValue: acMontlyAfterDegredationValue, grid : restOfGridAfterDegredation }
    currentYear ++;
    rate = newRate;
  }

  return monthlyDataPerYear;
}

//This function prepare object of monthName: Ac power produced , to be plotted in a graph
export function calculteProduct(acMonthly, monthlyAmount, rate){
  const data = calculateAcMonthlyForManyYears (acMonthly, monthlyAmount, rate);
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const chartData = {};
  let monthPower = [];

  for (const year in data) {
    for(let i=0; i< 12; i++){
      
      monthPower.push({month:months[i], power: Math.round(data[year].acMonthly[i])})
    }
    chartData[year] = monthPower;
    monthPower =[];
  }
  return chartData;

}

//This function calculate the value of the power for 25 years . The value of the power increase due to the secaltion of the price
//This calculation is prepared to be plotted in a graph
export function calculatePowerBillWithoutSolar(monthlyAmount, escalationRate = 0.025){
  const currentYear = new Date().getFullYear();
  const chartData = [];
  let year = currentYear;
  //First element in the chartData is pushed directly since we have the values. 
  //The next 24 years power value are calculated inside the loop
  chartData.push({year: currentYear.toString() , value: monthlyAmount  })
  
  for (let i = 1; i < 25; i++) {
    let valueAfterEscalation = chartData[i-1].value * (1 + escalationRate);
    chartData.push({year: (year + 1).toString(), value: Math.round(valueAfterEscalation) })
    year ++;
  }
  return chartData;
}

//This function prepare the value of the ac power generated by the solar power system for 25 years
// to be plotted in a graph
export function calculateAcPowerValue(acAnnual,rate, lifespan = 25) {
  const data = calculateAcAnnualForManyYears (acAnnual,rate);
  const currentYear =  new Date().getFullYear();
  let year = currentYear;
  const chartData = [];
  for (let i = 0; i < lifespan; i ++) {
    chartData.push({year: year.toString(), value: Math.round(data[year].amount)});
    year ++;
  }
  return chartData
}


// calculate system cost + taxes including rebate if defined
export function calculateSystemGrossCostAfterRebate(systemBaseCost, rebatePrc=0, rebateLimit=0) {
    const rebate = (systemBaseCost * rebatePrc) < rebateLimit ? systemBaseCost * rebatePrc : rebateLimit;
    return systemBaseCost * (1 + 0.13) - rebate;
  }

  // calculate system without taxes including rebate if defined
  export function calculateSystemNetCostAfterRebate(systemBaseCost, rebatePrc=0, rebateLimit=0) {
    const rebate = (systemBaseCost * rebatePrc) < rebateLimit ? systemBaseCost * rebatePrc : rebateLimit;
    return systemBaseCost - rebate;
  }


  export function calculateROI (profit, investment, projectLC = 25) {
    return profit / investment * 100 / projectLC;
  }

  export function totalSaving (acAnnual, rate) {
    const dataPerYear = calculateAcAnnualForManyYears(acAnnual, rate)
    //the average value of power produced for the system's lifespan.
    let sum = 0;
    for  (let year in dataPerYear) {
      sum += dataPerYear[year].amount;
    }
    return sum;
  }

  //this function calculate the total value of the power for 25 years without using solar system
  export function totalOriginal(monthlyBill, rate, escalationRate = 0.025, lifespan = 25) {
    const firstYearBill = 12 * monthlyBill;
    const yearlyConsumption = firstYearBill/rate;
    let yearlyBill = []
    yearlyBill.push(firstYearBill)
    for (let i = 1; i < lifespan; i++) {
      // Amount is calculated based on newly calculated bill factoring escalation rate
      let newRate = rate * ( 1 + escalationRate );
      
      yearlyBill.push( yearlyConsumption * newRate);
      rate = newRate;
    }
    const sum = yearlyBill.reduce((total,number) => total + number);
    return sum;
  }

  //This function calculate the average monthly power bill after using solar power system
  export function newBill (acMonthly, monthlyAmount, year, rate) {
    const yearsData = calculateAcMonthlyForManyYears(acMonthly, monthlyAmount, rate);
    const grid = yearsData[year].grid.reduce((total,value)=> total + value);
    return -1 * grid / 12;
  }

  export function calculatePayback(acAnnual, netCost, rate, lifespan = 25 ) {
    
    // calculate total saving based on degradation and escalation rate in 25 years
    const sum = totalSaving(acAnnual, rate);
    const avg = sum / lifespan;

    // return payBack value
    console.log('saving', sum, 'netCost', netCost,'avg', avg, 'payback', netCost / avg);
    return netCost / avg;
  };

  // monthly payment calculation based on percentage rate, priniple and number of years term
  export function calculateMonthlyPaiment(principal, percentageRate, term) {
    const lengthOfLoan = term * 12;
    const rate = percentageRate / 100 / 12;

    return (principal * rate) / (1 - (Math.pow((1 + rate), lengthOfLoan * -1)));
  }